/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hl7tdaveqncy3alqbjdsx6rbum.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-y5eygjprjjh7xnxp5ixqvu5vsu",
    "aws_cognito_identity_pool_id": "us-east-1:0a0e26a1-3b5d-45d9-bdb5-5437fc83b73d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VUJQSxf3X",
    "aws_user_pools_web_client_id": "tss4dgfdg62nu0e2q39lts7r6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL",
        "PROFILE"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "myfitrackr-storage-amplify154456-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
